spring:
  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/mybatistwo?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#    url: jdbc:mysql://121.199.53.182/chen?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai

    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8

    username: root
#    password: root
    password: rootlzh
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

logging:
  level:
    root: info
    com.lrm: debug
  file:
    name: log/blog-dev.log
server:
  port: 8082

mybatis:
  mapper-locations: classpath:mapper/*.xml

