package com.example.model;

public class Blog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.id
     *
     * @mbg.generated Sat Sep 26 18:40:47 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_blog.name
     *
     * @mbg.generated Sat Sep 26 18:40:47 CST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.id
     *
     * @return the value of t_blog.id
     *
     * @mbg.generated Sat Sep 26 18:40:47 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.id
     *
     * @param id the value for t_blog.id
     *
     * @mbg.generated Sat Sep 26 18:40:47 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_blog.name
     *
     * @return the value of t_blog.name
     *
     * @mbg.generated Sat Sep 26 18:40:47 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_blog.name
     *
     * @param name the value for t_blog.name
     *
     * @mbg.generated Sat Sep 26 18:40:47 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}